#!/usr/bin/python

import logging
from optparse import OptionParser
from gobject import threads_init, MainLoop
from dbus import SystemBus
from dbus.service import BusName
from dbus.mainloop.glib import DBusGMainLoop
from JobService import DBUS_PATH
from JobService.root import RootJobService
from JobService.util import IdleTimeout

# options
op = OptionParser()
op.add_option('--debug', action='store_true', dest='debug', default=False)
op.add_option('--no-enforce', action='store_false', dest='enforce', default=True)
(options, args) = op.parse_args()

# logging
level = logging.DEBUG if options.debug else logging.INFO
logging.basicConfig(level=level, datefmt="%H:%M:%S",
        format="%(asctime)s %(name)s %(levelname)s: %(message)s")
log = logging.getLogger('jobservice')
log.info("Starting up")

# start up!
DBusGMainLoop(set_as_default=True)
threads_init()
loop = MainLoop()
srv = RootJobService(
    BusName('com.ubuntu.JobService', bus=SystemBus()),
    DBUS_PATH,
    idle=IdleTimeout(loop, 300),
    enforce=options.enforce
)
loop.run()
