#!/usr/bin/python

import logging
from gobject import threads_init, MainLoop
from dbus import SystemBus
from dbus.service import BusName
from dbus.mainloop.glib import DBusGMainLoop
from JobService import DBUS_PATH
from JobService.root import RootJobService
from JobService.util import IdleTimeout

logging.basicConfig(level=logging.DEBUG,
        format="[%(asctime)s] %(levelname)-7s %(name)s: %(message)s")
log = logging.getLogger('jobservice')
log.info("Starting up")

DBusGMainLoop(set_as_default=True)
threads_init()

loop = MainLoop()
srv = RootJobService(
    BusName('com.ubuntu.JobService', bus=SystemBus()),
    DBUS_PATH,
    idle=IdleTimeout(loop, 300)
)
loop.run()
